# Generated by Django 3.0 on 2021-03-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0003_auto_20210302_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeraccount',
            name='username',
        ),
    ]
